### ISSUE TITLE
Music commands not working.

### ISSUE THREAD

**Issue by Yeahhahaha** [Cramenorn/RaptorSA#1]
It joins the music channel and then immediately leaves.

**Comment by Uthsho** [comment]
same problem here.

**Comment by MalwareWerewolf** [comment]
Have you installed FFmpeg ? Without it the bot doesn't work correctly, you also need to be in a voice channel.
I tested the bot and it is working perfectly, it joins in a voice channel and I can listen the music with it. The bot also needs administrator permissions and that role must be above every other role. 
For example:

![Roles](https://user-images.githubusercontent.com/43040746/63683914-fdc86c00-c7fb-11e9-9cce-cbe170259235.PNG)

In this case the bot can do everything so you should grant it every kind of permission.
If the bot doesn't execute a command, as expected, it will print in the console an error message.
