### ISSUE TITLE
Discord js 12

### ISSUE THREAD

**Issue by Jacob22092** [Cramenorn/RaptorSA#10]

**Comment by MalwareWerewolf** [comment]
Hi @Jacob22092,
I recently created a [page](https://github.com/Cramenorn/RaptorSA/wiki/Common-Issues) in the wiki section if you find other common issues, at the moment the discord.js will not be updated. Some packages will not work with the 12 version.

**Comment by Jacob22092** [comment]
> Hi @Jacob22092,
> I recently created a [page](https://github.com/Cramenorn/RaptorSA/wiki/Common-Issues) in the wiki section if you find other common issues, at the moment the discord.js will not be updated. Some packages will not work with the 12 version.

Ok thx for reply
