### ISSUE TITLE
Wrong README

### ISSUE THREAD

**Issue by EpicmonkeyGaming** [Cramenorn/RaptorSA#11]
Manual installation
You will need python 2.7 and FFmpeg, Discord.js now requires Node version greater than or equal to 12.0.0 

It seems all the files are .js why would you need python.

**Comment by MalwareWerewolf** [comment]
Hi @EpicmonkeyGaming ,
Node.js is built with GYP — cross-platform built tool written in Python. Also some other build steps are implemented in Python. So Python is required for building node from source.
