### ISSUE TITLE
Csgo Command (MIGHT BE BROKEN)

### ISSUE THREAD

**Issue by Sattishh** [Cramenorn/RaptorSA#12]
Hey!

I came across your github repository and was interested in the csgo.js file, I saw that you used exports and args[0] to write the profile, when I write this link in my browser, it just redirects me to tracker.gg. I think the csgo command might be broken.

**Comment by MalwareWerewolf** [comment]
Hi @Sattishh ,
the command **csgo** has been updated, you just need to type a **STEAMID64** with the command to get the csgo stats of an user.

Example:

![image](https://user-images.githubusercontent.com/43040746/84695363-020c7400-af4b-11ea-986f-d9907afd361b.png)

**Comment by Sattishh** [comment]
Ok that's great. Also, I'm trying to put this command in my bot, I don't use exports.run so I'm a bit confused on where you inputted e.g `if (message.content.startsWith())` 

Could you please help me :)

**Comment by MalwareWerewolf** [comment]
**exports.run** is used to run directly the command without calling every time `cmd.run(client, message, args, ops)`, **message** is loaded as a function parameter.

Also when you launch the bot, the commands and the events are loaded in the memory using [Enmap](https://www.npmjs.com/package/enmap). 

For example:
```node.js
client.commands = new Enmap();

fs.readdir("./commands/music/", (err, files) => {
  if (err) return console.error(err);
  files.forEach(file => {
    if (!file.endsWith(".js")) return;
    let props = require(`./commands/music/${file}`);
    let commandName = file.split(".")[0];
    console.log(`Attempting to load command ${commandName}`);
    client.commands.set(commandName, props);
  });
});
```

In other words, the bot is actually working in the following order: 
1. **index.js** (loads the commands and events)
2. **message.js** (manage the messages that the user can send to the bot)
3. run a command with the prefix **$** using **exports.run**

**Comment by Sattishh** [comment]
Ah okay, thanks for clearing it up. 👍
