### ISSUE TITLE
Could you add a unmute command?

### ISSUE THREAD

**Issue by ghost** [Cramenorn/RaptorSA#14]
I use your mute command could you make a unmute command?

**Comment by MalwareWerewolf** [comment]
Hello @K00L1000 ,
there is no need to add an unmute command, the user is automatically removed after the time that you specified.

Example:

![Capture](https://user-images.githubusercontent.com/43040746/94960308-f68d8a80-04f2-11eb-9c71-0acfb9fd3397.PNG)

You can also directly remove the role **muted** from user, in this way the user is no longer muted.
