### ISSUE TITLE
What is cx

### ISSUE THREAD

**Issue by AriaFantom** [Cramenorn/RaptorSA#2]
I don't understand short form

**Comment by MalwareWerewolf** [comment]
CX is the custom search engine ID to use for the request. [Here you can find the cx id](http://www.google.com/cse/manage/all) look for My search engines then choose from the list. [Other link](https://support.google.com/customsearch/answer/2649143?hl=en) from Google Support.

**Comment by AriaFantom** [comment]
I can't get the id when I click on the link it shows problem occurred
