### ISSUE TITLE
i get this error if i run index.js file after installing all the modules.

### ISSUE THREAD

**Issue by ashtonmths** [Cramenorn/RaptorSA#23]
[](url)
![Screenshot (1)](https://user-images.githubusercontent.com/68967455/99238781-29c87680-2820-11eb-9fce-2c2280e950c2.png)
i get this for all the folders
@Cramenorn

**Comment by MalwareWerewolf** [comment]
Hello @Subtilizer28 ,
did you try to execute the bot with the following command ```node src/index.js``` ? You have to go the **src** directory with the  ``` cd ```  command and type ``` node index.js``` , in all other cases is not going to work.
