### ISSUE TITLE
Use glob instead of looping over every folder

### ISSUE THREAD

**Issue by Murky-MoMo** [Cramenorn/RaptorSA#26]
on your src/index.js
you loop over every folder inside commands manually
looping over 5 times and not being able to just add a new category on the fly would be the disadvantage for this
i'd suggest you use a package like [glob](https://www.npmjs.com/package/glob)
the [usage part](https://www.npmjs.com/package/glob#usage) should explain you how to use it

**Comment by MalwareWerewolf** [comment]
Hi @Murky-MoMo ,
I checked the **glob** documentation but I would say that in this case it is not necessary to use another package unless there is absolutely no way around, but as I said this is not the case.

A possible solution could be the following:

```javascript
const Path = require("path");
const FS   = require("fs");
let Files  = [];

function ThroughDirectory(Directory) {
    FS.readdirSync(Directory).forEach(File => {
        const Absolute = Path.join(Directory, File);
        if (FS.statSync(Absolute).isDirectory()) return ThroughDirectory(Absolute);
        else return Files.push(Absolute);
    });
}

ThroughDirectory("./input/directory/");
```

It's pretty self-explanatory. There's an input directory, and it iterates through that. If one of the items is also a directory, go through that and so on. If it's a file, add the absolute path to the array.
