### ISSUE TITLE
Unable to play songs 

### ISSUE THREAD

**Issue by AriaFantom** [Cramenorn/RaptorSA#3]
(node:4448) UnhandledPromiseRejectionWarning: Error: This video is unavailable

**Comment by MalwareWerewolf** [comment]
Hi @Priyanshu348 ,
could you describe on which command this Exception has been thrown ?
Remember to install FFmpeg and grant to the bot every permission, there is a closed issue to a similar error https://github.com/Cramenorn/RaptorSA/issues/1#issuecomment-524797650

**Comment by AriaFantom** [comment]
The playtube command my discord I'd is 
Hackerz#5686

**Comment by AriaFantom** [comment]
(node:3065) UnhandledPromiseRejectionWarning: Error: This video is unavailable
    at request (/rbd/pnpm-volume/d910706f-0d7a-4606-86fa-843885fd0168/node_modules/.registry.npmjs.org/ytdl-core/0.21.1/node_modules/ytdl-core/lib/info.js:226:16)
    at PassThrough.Miniget.stream.on (/rbd/pnpm-volume/d910706f-0d7a-4606-86fa-843885fd0168/node_modules/.registry.npmjs.org/miniget/1.6.1/node_modules/miniget/dist/index.js:196:32)
    at PassThrough.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by AriaFantom** [comment]
I played a ncs video

**Comment by MalwareWerewolf** [comment]
It doesn't depend on the video but on node_modules packages versions. You need to update all node_modules by typing `npm update` in the root of your folder. In the meantime I updated the node modules to the latest in packages.json file, just in case there is a similar problem.

**Comment by AriaFantom** [comment]
The music quality is bad

**Comment by MalwareWerewolf** [comment]
There is a Bitrate setting on each voice channel which is defaulted to 64kbps. Click the gear sign next to the voice channel to go to the channel settings and make sure your Bitrate is as high as it will allow. According to GitHub issues on other repositories, Discord channels can reach 96kbps and partnered discord servers can be set up to 128kbps. The music quality also depends from the connection.
