### ISSUE TITLE
I want to export a variable

### ISSUE THREAD

**Issue by AriaFantom** [Cramenorn/RaptorSA#7]

**Comment by MalwareWerewolf** [comment]
In node.js you can export a variable in this way:
```javascript
// module.js
var name = "foobar";
// export it
exports.name = name;
```
Then in main.js
```javascript
//main.js
// get a reference to your required module
var myModule = require('./module');

// name is a member of myModule due to the export above
var name = myModule.name;
```

If you want a more detailed explanation about the topic, you can check the [Mozilla Docs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export).
