### ISSUE TITLE
I wonder something

### ISSUE THREAD

**Issue by PaleScribbles** [Cramenorn/RaptorSA#9]
Hi, when i write "npm install" on the cmd, i received a few console errors. Also i want to ask you a question more, can i install other a music npm? or  if i paste music name on the chat can i play music?

**Comment by MalwareWerewolf** [comment]
Hi @EnginZZZ, 
could you describe the error that you get on the cmd/terminal ? Before typing **npm install** you should install **ffmpeg** or the bot will not work.

> "Also i want to ask you a question more, can i install other a music npm?" 

If you need to install another node package yes it is possible, you just need to remove the opusscript package from the moment this is used to streaming and receiving audio, after that replace it with another.

> "or if i paste music name on the chat can i play music?" 

This is only possible if you trigger the bot with a specific command, you can't paste a song name without a command.

For example:

`$ytsearch [SongName]`

**Comment by PaleScribbles** [comment]
@Cramenorn 
_First, thanks a lot i will try it your suggestions._  :)
